# WELCOME TO NUMPY

In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,6,37777,7]],np.int32)

In [3]:
myarr

array([[    3,     6, 37777,     7]])

In [4]:
myarr[0,1]

6

In [5]:
myarr.shape

(1, 4)

In [6]:
myarr.dtype

dtype('int32')

In [7]:
myarr[0,1] = 45

In [8]:
myarr

array([[    3,    45, 37777,     7]])


# Array Creation: Conversion from other Python structures

In [9]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])

In [10]:
listarray


array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [11]:
listarray.dtype

dtype('int32')

In [12]:
listarray.shape

(3, 3)

In [13]:
listarray.size

9

In [14]:
np.array({32,33,34})

array({32, 33, 34}, dtype=object)

# Intrinsic numpy array creation objects

In [15]:
zeros = np.zeros((2,5))

In [16]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
zeros.dtype

dtype('float64')

In [18]:
zeros.shape

(2, 5)

In [19]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
rng = np.arange(15)

In [21]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
lspace = np.linspace(1,5,12)

In [23]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [24]:
lspace = np.linspace(1,4,4)

In [25]:
lspace

array([1., 2., 3., 4.])

In [26]:
emp =np.empty((4,6))

In [27]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        3.11522054e-307, 1.42413555e-306, 1.78019082e-306],
       [1.37959740e-306, 6.23057349e-307, 1.02360935e-306,
        1.69120416e-306, 1.78022342e-306, 6.23058028e-307],
       [1.06811422e-306, 9.45699680e-308, 1.11258854e-306,
        1.11261502e-306, 1.42410839e-306, 7.56597770e-307],
       [6.23059726e-307, 1.42419530e-306, 7.56602523e-307,
        1.29061821e-306, 7.23168527e-308, 2.56765117e-312]])

In [28]:
emp_like = np.empty_like(lspace)

In [29]:
emp_like

array([1., 2., 3., 4.])

In [30]:
ide = np.identity(45)

In [31]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [32]:
ide.shape

(45, 45)

In [33]:
arr = np.arange(99)

In [34]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [35]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [37]:
arr = arr.reshape(3,33)

In [38]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [41]:
arr = arr.ravel()

In [42]:
arr.shape

(99,)

# Axis

In [43]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [44]:
arr = np.array(x)

In [45]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [46]:
arr.sum(axis=0)

array([12,  8,  9])

In [48]:
arr.sum(axis=1)

array([ 6, 15,  8])

In [50]:
arr.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [51]:
arr.flat

In [53]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [54]:
arr.ndim

2

In [55]:
arr.size

9

In [56]:
arr.nbytes

36

In [57]:
one = np.array([1,3,4,634,2])

In [58]:
one.argmax()

3

In [59]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [60]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [61]:
arr.argmin()

8

In [62]:
arr.argmax()

6

In [63]:
arr.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [64]:
arr.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [65]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [67]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [69]:
arr.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [71]:
arr2 = np.array([[1,2,1],[4,0,6],[8,1,0]])

In [72]:
arr + arr2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [73]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [74]:
arr2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [75]:
arr*arr2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [76]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [77]:
arr.sum()

29

In [78]:
arr.max()

7

In [79]:
arr.min()

0

In [80]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [81]:
np.where(arr>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [82]:
tuple(np.where(arr>5))

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [83]:
np.count_nonzero(arr)

8

In [84]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [85]:
import sys

In [87]:
py_ar = [0,4,55,2] 

In [88]:
np_ar = np.array(py_ar)

In [90]:
sys.getsizeof(1) * len(py_ar)

112

In [92]:
np_ar.itemsize * np_ar.size

16

In [93]:
np_ar.tolist()

[0, 4, 55, 2]